context:
  version: "1.3.0"

package:
  name: deadnix
  version: ${{ version }}

source:
  url: https://github.com/astro/deadnix/archive/v${{ version }}.tar.gz
  sha256: 580d53eebb8c488e53be78b578ba85fc8389b8fa40435b1f11253b66ca290e7c

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - deadnix --help

about:
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Scan Nix files for dead code
  homepage: https://github.com/astro/deadnix
  repository: https://github.com/astro/deadnix

extra:
  recipe-maintainers:
    - danielnachun
